services:
  db:
    image: postgres:16
    restart: always
    container_name: jobboard_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobboard
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
